### ISSUE TITLE
La fonction somme retourne une multiplcation

### ISSUE THREAD

**Issue by prof-moevus-a24** [prof-moevus-a24/test#1]
https://github.com/prof-moevus-a24/test/blob/b82c7a010ec0a88ba6dd1e90b583dbbb75a0068a/maFonction.kt#L2

Il faudrait tester voir si ç est ce qu'on veut. SInon il faut refactoriser

**Comment by prof-moevus** [comment]
C'est carrément une erreur !! Qui a fait ça ? 😅

**Comment by prof-moevus** [comment]
<img width="738" alt="Screenshot 2024-11-13 at 9 49 26 AM" src="https://github.com/user-attachments/assets/20f39ce3-0804-4496-b5fb-27d8a1db5398">
c'est toi 😬

**Comment by prof-moevus-a24** [comment]
<img width="738" alt="Screenshot 2024-11-13 at 9 49 26 AM" src="https://github.com/user-attachments/assets/20f39ce3-0804-4496-b5fb-27d8a1db5398">

c'est toi 😬 @prof-moevus
